import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar' | 'fr' | 'ber';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
  isRTL: boolean;
  direction: 'ltr' | 'rtl';
  fontClass: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.quiz': 'Political Quiz',
    'nav.candidates': 'Candidates',
    'nav.policies': 'Policy Tracker',
    'nav.events': 'Events',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.retry': 'Try Again',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.view': 'View',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.share': 'Share',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    
    // Home page
    'home.title': 'Your Vote Matters',
    'home.subtitle': 'صوتك يهم',
    'home.hero.title': 'Empower Your Democratic Voice',
    'home.hero.subtitle': 'Morocco\'s Premier Civic Engagement Platform',
    'home.hero.description': 'Discover your political alignment, explore candidates, track policy promises, and participate in Morocco\'s democratic future through our comprehensive, research-backed platform.',
    'home.hero.cta.primary': 'Take Political Quiz',
    'home.hero.cta.secondary': 'Explore Candidates',
    'home.stats.users': 'Active Citizens',
    'home.stats.candidates': 'Verified Candidates',
    'home.stats.parties': 'Political Parties',
    'home.stats.satisfaction': 'User Satisfaction',
    'home.features.title': 'Comprehensive Democratic Tools',
    'home.features.subtitle': 'Everything you need to make informed political decisions',
    'home.features.quiz.title': 'Political Compass',
    'home.features.quiz.description': 'Discover which political parties align with your values through our scientifically-designed assessment.',
    'home.features.candidates.title': 'Candidate Profiles',
    'home.features.candidates.description': 'Explore detailed information about candidates in your region with verified backgrounds and positions.',
    'home.features.policies.title': 'Promise Tracker',
    'home.features.policies.description': 'Monitor political promises and track whether parties deliver on their commitments to voters.',
    'home.features.events.title': 'Civic Events',
    'home.features.events.description': 'Stay informed about debates, town halls, and political events happening in your community.',
    'home.cta.title': 'Join Morocco\'s Democratic Renaissance',
    'home.cta.description': 'Be part of a movement that strengthens democracy through informed participation and civic engagement.',
    'home.cta.button': 'Start Your Journey',
    
    // Quiz
    'quiz.title': 'Political Compass Assessment',
    'quiz.subtitle': 'Discover Your Political Alignment',
    'quiz.description': 'Answer questions about key political issues to find which Moroccan parties best represent your views.',
    'quiz.type.short': 'Quick Assessment',
    'quiz.type.full': 'Comprehensive Analysis',
    'quiz.type.short.description': '10 essential questions • 3 minutes',
    'quiz.type.full.description': '15 detailed questions • 5 minutes',
    'quiz.type.short.detail': 'Perfect for a quick political alignment overview',
    'quiz.type.full.detail': 'In-depth analysis of your political perspectives',
    'quiz.question.counter': 'Question {current} of {total}',
    'quiz.progress': '{percent}% Complete',
    'quiz.category.economic': 'Economic Policy',
    'quiz.category.social': 'Social Issues',
    'quiz.category.foreign': 'Foreign Policy',
    'quiz.category.environment': 'Environment',
    'quiz.category.education': 'Education & Culture',
    'quiz.category.healthcare': 'Healthcare',
    'quiz.category.technology': 'Technology & Rights',
    'quiz.answers.strongly_disagree': 'Strongly Disagree',
    'quiz.answers.disagree': 'Disagree',
    'quiz.answers.neutral': 'Neutral',
    'quiz.answers.agree': 'Agree',
    'quiz.answers.strongly_agree': 'Strongly Agree',
    'quiz.results.title': 'Your Political Alignment',
    'quiz.results.subtitle': 'Based on your responses, here\'s how you align with Moroccan political parties',
    'quiz.results.match': '{percent}% Match',
    'quiz.results.retake': 'Retake Assessment',
    'quiz.results.share': 'Share Results',
    'quiz.results.download': 'Download Report',
    'quiz.results.disclaimer': 'Results are based on party manifestos and public positions. Political views are complex and may not be fully captured by this assessment.',
    
    // Candidates
    'candidates.title': 'Candidate Directory',
    'candidates.subtitle': 'Know Your Representatives',
    'candidates.description': 'Explore detailed profiles of candidates running in your region with verified information and policy positions.',
    'candidates.search.placeholder': 'Search candidates by name...',
    'candidates.filter.region': 'Select Region',
    'candidates.filter.party': 'Select Party',
    'candidates.filter.all_regions': 'All Regions',
    'candidates.filter.all_parties': 'All Parties',
    'candidates.location.detect': 'Use My Location',
    'candidates.location.detected': 'Showing candidates for: {location}',
    'candidates.count': 'Showing {count} candidates',
    'candidates.age': 'Age {age}',
    'candidates.experience': 'Experience',
    'candidates.view_profile': 'View Full Profile',
    'candidates.no_results': 'No candidates found',
    'candidates.no_results.description': 'Try adjusting your search criteria or check back later',
    
    // Policies
    'policies.title': 'Policy Promise Tracker',
    'policies.subtitle': 'Accountability Through Transparency',
    'policies.description': 'Track political promises and see how well parties deliver on their commitments to Moroccan citizens.',
    'policies.search.placeholder': 'Search policy promises...',
    'policies.filter.status': 'Filter by Status',
    'policies.filter.category': 'Filter by Category',
    'policies.filter.party': 'Filter by Party',
    'policies.status.completed': 'Completed',
    'policies.status.in_progress': 'In Progress',
    'policies.status.not_started': 'Not Started',
    'policies.status.broken': 'Broken Promise',
    'policies.count': 'Showing {count} policy promises',
    'policies.promised_date': 'Promised: {date}',
    'policies.progress': 'Progress: {percent}%',
    'policies.sources': 'Sources:',
    'policies.no_results': 'No policies found',
    'policies.no_results.description': 'Try adjusting your search criteria',
    
    // Events
    'events.title': 'Political Events Calendar',
    'events.subtitle': 'Stay Engaged',
    'events.description': 'Discover upcoming political events, debates, and civic engagement opportunities in your region.',
    'events.filter.type': 'Event Type',
    'events.filter.region': 'Region',
    'events.filter.date': 'From Date',
    'events.type.debate': 'Debate',
    'events.type.town_hall': 'Town Hall',
    'events.type.rally': 'Rally',
    'events.type.info_session': 'Info Session',
    'events.count': 'Showing {count} events',
    'events.attendees': '{count} attendees',
    'events.max_attendees': ' / {max} max',
    'events.organized_by': 'Organized by: {organizer}',
    'events.add_calendar': 'Add to Calendar',
    'events.register': 'Register',
    'events.view_details': 'View Details',
    'events.online': 'Online',
    'events.past_event': 'Past Event',
    'events.no_results': 'No events found',
    'events.no_results.description': 'Try adjusting your search criteria or check back later for new events',
    
    // Footer
    'footer.description': 'Empowering Moroccan citizens to make informed voting decisions through technology, transparency, and civic engagement.',
    'footer.links.about': 'About Us',
    'footer.links.how_it_works': 'How It Works',
    'footer.links.privacy': 'Privacy Policy',
    'footer.links.terms': 'Terms of Service',
    'footer.support.help': 'Help Center',
    'footer.support.contact': 'Contact Us',
    'footer.support.report': 'Report Issue',
    'footer.support.feedback': 'Feedback',
    'footer.copyright': '© 2025 Your Vote Matters Platform. Made with ❤️ for Morocco.',
    'footer.tagline': 'Promoting transparency and democratic participation',
  },
  
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.quiz': 'الاختبار السياسي',
    'nav.candidates': 'المرشحون',
    'nav.policies': 'متتبع السياسات',
    'nav.events': 'الأحداث',
    'nav.about': 'حول',
    'nav.contact': 'اتصل بنا',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.retry': 'حاول مرة أخرى',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.submit': 'إرسال',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.clear': 'مسح',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.continue': 'متابعة',
    'common.finish': 'إنهاء',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.view': 'عرض',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.share': 'مشاركة',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.copy': 'نسخ',
    'common.copied': 'تم النسخ!',
    
    // Home page
    'home.title': 'صوتك يهم',
    'home.subtitle': 'Your Vote Matters',
    'home.hero.title': 'قوّي صوتك الديمقراطي',
    'home.hero.subtitle': 'منصة المغرب الرائدة للمشاركة المدنية',
    'home.hero.description': 'اكتشف توجهك السياسي، استكشف المرشحين، تتبع الوعود السياسية، وشارك في مستقبل المغرب الديمقراطي من خلال منصتنا الشاملة المدعومة بالبحث العلمي.',
    'home.hero.cta.primary': 'خذ الاختبار السياسي',
    'home.hero.cta.secondary': 'استكشف المرشحين',
    'home.stats.users': 'مواطن نشط',
    'home.stats.candidates': 'مرشح موثق',
    'home.stats.parties': 'حزب سياسي',
    'home.stats.satisfaction': 'رضا المستخدمين',
    'home.features.title': 'أدوات ديمقراطية شاملة',
    'home.features.subtitle': 'كل ما تحتاجه لاتخاذ قرارات سياسية مدروسة',
    'home.features.quiz.title': 'البوصلة السياسية',
    'home.features.quiz.description': 'اكتشف الأحزاب السياسية التي تتماشى مع قيمك من خلال تقييمنا المصمم علمياً.',
    'home.features.candidates.title': 'ملفات المرشحين',
    'home.features.candidates.description': 'استكشف معلومات مفصلة عن المرشحين في منطقتك مع خلفيات ومواقف موثقة.',
    'home.features.policies.title': 'متتبع الوعود',
    'home.features.policies.description': 'راقب الوعود السياسية وتتبع ما إذا كانت الأحزاب تفي بالتزاماتها تجاه الناخبين.',
    'home.features.events.title': 'الأحداث المدنية',
    'home.features.events.description': 'ابق على اطلاع بالمناقشات وقاعات البلدية والأحداث السياسية في مجتمعك.',
    'home.cta.title': 'انضم إلى النهضة الديمقراطية المغربية',
    'home.cta.description': 'كن جزءاً من حركة تقوي الديمقراطية من خلال المشاركة المدروسة والمشاركة المدنية.',
    'home.cta.button': 'ابدأ رحلتك',
    
    // Quiz
    'quiz.title': 'تقييم البوصلة السياسية',
    'quiz.subtitle': 'اكتشف توجهك السياسي',
    'quiz.description': 'أجب على أسئلة حول القضايا السياسية الرئيسية لتجد الأحزاب المغربية التي تمثل آراءك بشكل أفضل.',
    'quiz.type.short': 'تقييم سريع',
    'quiz.type.full': 'تحليل شامل',
    'quiz.type.short.description': '10 أسئلة أساسية • 3 دقائق',
    'quiz.type.full.description': '15 سؤال مفصل • 5 دقائق',
    'quiz.type.short.detail': 'مثالي للحصول على نظرة عامة سريعة على التوجه السياسي',
    'quiz.type.full.detail': 'تحليل متعمق لوجهات نظرك السياسية',
    'quiz.question.counter': 'السؤال {current} من {total}',
    'quiz.progress': 'مكتمل {percent}%',
    'quiz.category.economic': 'السياسة الاقتصادية',
    'quiz.category.social': 'القضايا الاجتماعية',
    'quiz.category.foreign': 'السياسة الخارجية',
    'quiz.category.environment': 'البيئة',
    'quiz.category.education': 'التعليم والثقافة',
    'quiz.category.healthcare': 'الرعاية الصحية',
    'quiz.category.technology': 'التكنولوجيا والحقوق',
    'quiz.answers.strongly_disagree': 'أعارض بشدة',
    'quiz.answers.disagree': 'أعارض',
    'quiz.answers.neutral': 'محايد',
    'quiz.answers.agree': 'أوافق',
    'quiz.answers.strongly_agree': 'أوافق بشدة',
    'quiz.results.title': 'توجهك السياسي',
    'quiz.results.subtitle': 'بناءً على إجاباتك، إليك كيف تتماشى مع الأحزاب السياسية المغربية',
    'quiz.results.match': 'تطابق {percent}%',
    'quiz.results.retake': 'إعادة التقييم',
    'quiz.results.share': 'مشاركة النتائج',
    'quiz.results.download': 'تحميل التقرير',
    'quiz.results.disclaimer': 'النتائج مبنية على برامج الأحزاب والمواقف العامة. الآراء السياسية معقدة وقد لا يتم التقاطها بالكامل من خلال هذا التقييم.',
    
    // Candidates
    'candidates.title': 'دليل المرشحين',
    'candidates.subtitle': 'اعرف ممثليك',
    'candidates.description': 'استكشف ملفات مفصلة للمرشحين المترشحين في منطقتك مع معلومات ومواقف سياسية موثقة.',
    'candidates.search.placeholder': 'البحث عن المرشحين بالاسم...',
    'candidates.filter.region': 'اختر المنطقة',
    'candidates.filter.party': 'اختر الحزب',
    'candidates.filter.all_regions': 'جميع المناطق',
    'candidates.filter.all_parties': 'جميع الأحزاب',
    'candidates.location.detect': 'استخدم موقعي',
    'candidates.location.detected': 'عرض المرشحين لـ: {location}',
    'candidates.count': 'عرض {count} مرشح',
    'candidates.age': 'العمر {age}',
    'candidates.experience': 'الخبرة',
    'candidates.view_profile': 'عرض الملف الكامل',
    'candidates.no_results': 'لم يتم العثور على مرشحين',
    'candidates.no_results.description': 'جرب تعديل معايير البحث أو تحقق مرة أخرى لاحقاً',
    
    // Policies
    'policies.title': 'متتبع الوعود السياسية',
    'policies.subtitle': 'المساءلة من خلال الشفافية',
    'policies.description': 'تتبع الوعود السياسية وشاهد مدى جودة وفاء الأحزاب بالتزاماتها تجاه المواطنين المغاربة.',
    'policies.search.placeholder': 'البحث في الوعود السياسية...',
    'policies.filter.status': 'تصفية حسب الحالة',
    'policies.filter.category': 'تصفية حسب الفئة',
    'policies.filter.party': 'تصفية حسب الحزب',
    'policies.status.completed': 'مكتمل',
    'policies.status.in_progress': 'قيد التنفيذ',
    'policies.status.not_started': 'لم يبدأ',
    'policies.status.broken': 'وعد مكسور',
    'policies.count': 'عرض {count} وعد سياسي',
    'policies.promised_date': 'وُعد في: {date}',
    'policies.progress': 'التقدم: {percent}%',
    'policies.sources': 'المصادر:',
    'policies.no_results': 'لم يتم العثور على سياسات',
    'policies.no_results.description': 'جرب تعديل معايير البحث',
    
    // Events
    'events.title': 'تقويم الأحداث السياسية',
    'events.subtitle': 'ابق منخرطاً',
    'events.description': 'اكتشف الأحداث السياسية القادمة والمناقشات وفرص المشاركة المدنية في منطقتك.',
    'events.filter.type': 'نوع الحدث',
    'events.filter.region': 'المنطقة',
    'events.filter.date': 'من تاريخ',
    'events.type.debate': 'مناقشة',
    'events.type.town_hall': 'قاعة البلدية',
    'events.type.rally': 'تجمع',
    'events.type.info_session': 'جلسة معلومات',
    'events.count': 'عرض {count} حدث',
    'events.attendees': '{count} حاضر',
    'events.max_attendees': ' / {max} كحد أقصى',
    'events.organized_by': 'منظم من قبل: {organizer}',
    'events.add_calendar': 'إضافة للتقويم',
    'events.register': 'تسجيل',
    'events.view_details': 'عرض التفاصيل',
    'events.online': 'عبر الإنترنت',
    'events.past_event': 'حدث سابق',
    'events.no_results': 'لم يتم العثور على أحداث',
    'events.no_results.description': 'جرب تعديل معايير البحث أو تحقق مرة أخرى لاحقاً للأحداث الجديدة',
    
    // Footer
    'footer.description': 'تمكين المواطنين المغاربة من اتخاذ قرارات تصويت مدروسة من خلال التكنولوجيا والشفافية والمشاركة المدنية.',
    'footer.links.about': 'حولنا',
    'footer.links.how_it_works': 'كيف يعمل',
    'footer.links.privacy': 'سياسة الخصوصية',
    'footer.links.terms': 'شروط الخدمة',
    'footer.support.help': 'مركز المساعدة',
    'footer.support.contact': 'اتصل بنا',
    'footer.support.report': 'الإبلاغ عن مشكلة',
    'footer.support.feedback': 'ملاحظات',
    'footer.copyright': '© 2025 منصة صوتك يهم. صُنع بـ ❤️ للمغرب.',
    'footer.tagline': 'تعزيز الشفافية والمشاركة الديمقراطية',
  },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.quiz': 'Quiz Politique',
    'nav.candidates': 'Candidats',
    'nav.policies': 'Suivi des Politiques',
    'nav.events': 'Événements',
    'nav.about': 'À Propos',
    'nav.contact': 'Contact',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
    'common.retry': 'Réessayer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.submit': 'Soumettre',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.clear': 'Effacer',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.continue': 'Continuer',
    'common.finish': 'Terminer',
    'common.close': 'Fermer',
    'common.open': 'Ouvrir',
    'common.view': 'Voir',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.share': 'Partager',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.copy': 'Copier',
    'common.copied': 'Copié !',
    
    // Home page
    'home.title': 'Votre Vote Compte',
    'home.subtitle': 'صوتك يهم',
    'home.hero.title': 'Renforcez Votre Voix Démocratique',
    'home.hero.subtitle': 'Plateforme Marocaine Première d\'Engagement Civique',
    'home.hero.description': 'Découvrez votre alignement politique, explorez les candidats, suivez les promesses politiques, et participez à l\'avenir démocratique du Maroc grâce à notre plateforme complète soutenue par la recherche.',
    'home.hero.cta.primary': 'Passer le Quiz Politique',
    'home.hero.cta.secondary': 'Explorer les Candidats',
    'home.stats.users': 'Citoyens Actifs',
    'home.stats.candidates': 'Candidats Vérifiés',
    'home.stats.parties': 'Partis Politiques',
    'home.stats.satisfaction': 'Satisfaction Utilisateur',
    'home.features.title': 'Outils Démocratiques Complets',
    'home.features.subtitle': 'Tout ce dont vous avez besoin pour prendre des décisions politiques éclairées',
    'home.features.quiz.title': 'Boussole Politique',
    'home.features.quiz.description': 'Découvrez quels partis politiques s\'alignent avec vos valeurs grâce à notre évaluation conçue scientifiquement.',
    'home.features.candidates.title': 'Profils de Candidats',
    'home.features.candidates.description': 'Explorez des informations détaillées sur les candidats de votre région avec des antécédents et positions vérifiés.',
    'home.features.policies.title': 'Suivi des Promesses',
    'home.features.policies.description': 'Surveillez les promesses politiques et suivez si les partis tiennent leurs engagements envers les électeurs.',
    'home.features.events.title': 'Événements Civiques',
    'home.features.events.description': 'Restez informé des débats, assemblées publiques et événements politiques dans votre communauté.',
    'home.cta.title': 'Rejoignez la Renaissance Démocratique du Maroc',
    'home.cta.description': 'Faites partie d\'un mouvement qui renforce la démocratie par la participation éclairée et l\'engagement civique.',
    'home.cta.button': 'Commencez Votre Parcours',
    
    // Quiz
    'quiz.title': 'Évaluation de la Boussole Politique',
    'quiz.subtitle': 'Découvrez Votre Alignement Politique',
    'quiz.description': 'Répondez aux questions sur les enjeux politiques clés pour trouver quels partis marocains représentent le mieux vos opinions.',
    'quiz.type.short': 'Évaluation Rapide',
    'quiz.type.full': 'Analyse Complète',
    'quiz.type.short.description': '10 questions essentielles • 3 minutes',
    'quiz.type.full.description': '15 questions détaillées • 5 minutes',
    'quiz.type.short.detail': 'Parfait pour un aperçu rapide de l\'alignement politique',
    'quiz.type.full.detail': 'Analyse approfondie de vos perspectives politiques',
    'quiz.question.counter': 'Question {current} sur {total}',
    'quiz.progress': '{percent}% Terminé',
    'quiz.category.economic': 'Politique Économique',
    'quiz.category.social': 'Questions Sociales',
    'quiz.category.foreign': 'Politique Étrangère',
    'quiz.category.environment': 'Environnement',
    'quiz.category.education': 'Éducation et Culture',
    'quiz.category.healthcare': 'Santé',
    'quiz.category.technology': 'Technologie et Droits',
    'quiz.answers.strongly_disagree': 'Fortement en Désaccord',
    'quiz.answers.disagree': 'En Désaccord',
    'quiz.answers.neutral': 'Neutre',
    'quiz.answers.agree': 'D\'Accord',
    'quiz.answers.strongly_agree': 'Fortement d\'Accord',
    'quiz.results.title': 'Votre Alignement Politique',
    'quiz.results.subtitle': 'Basé sur vos réponses, voici comment vous vous alignez avec les partis politiques marocains',
    'quiz.results.match': '{percent}% de Correspondance',
    'quiz.results.retake': 'Refaire l\'Évaluation',
    'quiz.results.share': 'Partager les Résultats',
    'quiz.results.download': 'Télécharger le Rapport',
    'quiz.results.disclaimer': 'Les résultats sont basés sur les manifestes des partis et les positions publiques. Les opinions politiques sont complexes et peuvent ne pas être entièrement capturées par cette évaluation.',
    
    // Candidates
    'candidates.title': 'Répertoire des Candidats',
    'candidates.subtitle': 'Connaissez Vos Représentants',
    'candidates.description': 'Explorez des profils détaillés des candidats se présentant dans votre région avec des informations et positions politiques vérifiées.',
    'candidates.search.placeholder': 'Rechercher des candidats par nom...',
    'candidates.filter.region': 'Sélectionner la Région',
    'candidates.filter.party': 'Sélectionner le Parti',
    'candidates.filter.all_regions': 'Toutes les Régions',
    'candidates.filter.all_parties': 'Tous les Partis',
    'candidates.location.detect': 'Utiliser Ma Position',
    'candidates.location.detected': 'Affichage des candidats pour : {location}',
    'candidates.count': 'Affichage de {count} candidats',
    'candidates.age': 'Âge {age}',
    'candidates.experience': 'Expérience',
    'candidates.view_profile': 'Voir le Profil Complet',
    'candidates.no_results': 'Aucun candidat trouvé',
    'candidates.no_results.description': 'Essayez d\'ajuster vos critères de recherche ou revenez plus tard',
    
    // Policies
    'policies.title': 'Suivi des Promesses Politiques',
    'policies.subtitle': 'Responsabilité par la Transparence',
    'policies.description': 'Suivez les promesses politiques et voyez à quel point les partis tiennent leurs engagements envers les citoyens marocains.',
    'policies.search.placeholder': 'Rechercher des promesses politiques...',
    'policies.filter.status': 'Filtrer par Statut',
    'policies.filter.category': 'Filtrer par Catégorie',
    'policies.filter.party': 'Filtrer par Parti',
    'policies.status.completed': 'Terminé',
    'policies.status.in_progress': 'En Cours',
    'policies.status.not_started': 'Pas Commencé',
    'policies.status.broken': 'Promesse Brisée',
    'policies.count': 'Affichage de {count} promesses politiques',
    'policies.promised_date': 'Promis le : {date}',
    'policies.progress': 'Progrès : {percent}%',
    'policies.sources': 'Sources :',
    'policies.no_results': 'Aucune politique trouvée',
    'policies.no_results.description': 'Essayez d\'ajuster vos critères de recherche',
    
    // Events
    'events.title': 'Calendrier des Événements Politiques',
    'events.subtitle': 'Restez Engagé',
    'events.description': 'Découvrez les événements politiques à venir, les débats et les opportunités d\'engagement civique dans votre région.',
    'events.filter.type': 'Type d\'Événement',
    'events.filter.region': 'Région',
    'events.filter.date': 'À partir du',
    'events.type.debate': 'Débat',
    'events.type.town_hall': 'Assemblée Publique',
    'events.type.rally': 'Rassemblement',
    'events.type.info_session': 'Session d\'Information',
    'events.count': 'Affichage de {count} événements',
    'events.attendees': '{count} participants',
    'events.max_attendees': ' / {max} max',
    'events.organized_by': 'Organisé par : {organizer}',
    'events.add_calendar': 'Ajouter au Calendrier',
    'events.register': 'S\'inscrire',
    'events.view_details': 'Voir les Détails',
    'events.online': 'En Ligne',
    'events.past_event': 'Événement Passé',
    'events.no_results': 'Aucun événement trouvé',
    'events.no_results.description': 'Essayez d\'ajuster vos critères de recherche ou revenez plus tard pour de nouveaux événements',
    
    // Footer
    'footer.description': 'Permettre aux citoyens marocains de prendre des décisions de vote éclairées grâce à la technologie, la transparence et l\'engagement civique.',
    'footer.links.about': 'À Propos',
    'footer.links.how_it_works': 'Comment Ça Marche',
    'footer.links.privacy': 'Politique de Confidentialité',
    'footer.links.terms': 'Conditions d\'Utilisation',
    'footer.support.help': 'Centre d\'Aide',
    'footer.support.contact': 'Nous Contacter',
    'footer.support.report': 'Signaler un Problème',
    'footer.support.feedback': 'Commentaires',
    'footer.copyright': '© 2025 Plateforme Votre Vote Compte. Fait avec ❤️ pour le Maroc.',
    'footer.tagline': 'Promouvoir la transparence et la participation démocratique',
  },
  
  ber: {
    // Navigation
    'nav.home': 'ⴰⵙⵏⵓⴱⴳ',
    'nav.quiz': 'ⴰⵙⵙⴰⵖ ⴰⵙⵔⵜⴰⵏ',
    'nav.candidates': 'ⵉⵎⵙⵙⴰⵔⴰⵏ',
    'nav.policies': 'ⴰⵎⴹⴼⴰⵕ ⵏ ⵜⵙⵔⵜⵉⵏ',
    'nav.events': 'ⵜⵉⵎⵙⴰⵔⵉⵏ',
    'nav.about': 'ⵅⴼ',
    'nav.contact': 'ⴰⵎⵢⴰⵡⴰⴹ',
    
    // Common
    'common.loading': 'ⴰⵔ ⵉⵜⵜⵓⵙⴰⵍⵢ...',
    'common.error': 'ⵉⵍⵍⴰ ⵓⵣⴳⵍ',
    'common.retry': 'ⴰⵔⵎ ⴰⵢⴰⴷ',
    'common.save': 'ⵃⴹⵓ',
    'common.cancel': 'ⵙⵙⵓⵇⴼ',
    'common.submit': 'ⴰⵣⵏ',
    'common.search': 'ⵔⵣⵓ',
    'common.filter': 'ⵙⴼⵍ',
    'common.clear': 'ⵙⴼⴹ',
    'common.all': 'ⴰⴽⴽⵯ',
    'common.none': 'ⴰⵔⴰ',
    'common.yes': 'ⵢⴰⵀ',
    'common.no': 'ⵓⵀⵓ',
    'common.back': 'ⵓⵖⵓⵍ',
    'common.next': 'ⴷ ⵓⴹⴼⵉⵔ',
    'common.previous': 'ⴰⵣⵡⴰⵔⵓ',
    'common.continue': 'ⴽⵎⵍ',
    'common.finish': 'ⵎⴷ',
    'common.close': 'ⵔⴳⵍ',
    'common.open': 'ⵍⴷⵉ',
    'common.view': 'ⵥⵕ',
    'common.edit': 'ⵙⵏⴼⵍ',
    'common.delete': 'ⴽⴽⵙ',
    'common.share': 'ⴱⴹⵓ',
    'common.download': 'ⴰⴳⵎ',
    'common.upload': 'ⴰⵍⵙ',
    'common.copy': 'ⵏⵖⵍ',
    'common.copied': 'ⵉⵜⵜⵓⵏⵖⵍ!',
    
    // Home page
    'home.title': 'ⴰⵙⵙⴰⵖ ⵏⵏⴽ ⵉⵙⵙⴰⵡⴰⵍ',
    'home.subtitle': 'Your Vote Matters',
    'home.hero.title': 'ⵙⵙⵏⵖⵓⵔ ⴰⵖⵔⵓ ⵏⵏⴽ ⴰⴷⵉⵎⵓⵇⵔⴰⵟⵉⵢ',
    'home.hero.subtitle': 'ⵜⴰⵏⴰⴱⴰⴹⵜ ⵜⴰⵎⵖⵔⵉⴱⵉⵜ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ ⵏ ⵓⴷⵔⴰⵡ ⴰⵎⴷⴰⵏ',
    'home.hero.description': 'ⴰⴼ ⴰⵙⵙⴰⵔⵓ ⵏⵏⴽ ⴰⵙⵔⵜⴰⵏ, ⵙⵙⵉⵔⵉⵎ ⵉⵎⵙⵙⴰⵔⴰⵏ, ⴹⴼⵕ ⵉⵡⵓⵔⵉⵡⵏ ⵉⵙⵔⵜⴰⵏⵏ, ⴷ ⴰⴷⵔⴰⵡ ⴳ ⵓⵙⴰⵜⵉ ⴰⴷⵉⵎⵓⵇⵔⴰⵟⵉⵢ ⵏ ⵍⵎⵖⵔⵉⴱ ⵙ ⵜⵏⴰⴱⴰⴹⵜ ⵏⵏⵖ ⵜⴰⵎⵓⵔⵙⵜ ⵉⵜⵜⵓⵙⵙⴽⴰⵔⵏ ⵙ ⵓⵔⵣⵣⵓ.',
    'home.hero.cta.primary': 'ⵙⴽⵔ ⴰⵙⵙⴰⵖ ⴰⵙⵔⵜⴰⵏ',
    'home.hero.cta.secondary': 'ⵙⵙⵉⵔⵉⵎ ⵉⵎⵙⵙⴰⵔⴰⵏ',
    'home.stats.users': 'ⵉⵎⵣⴷⴰⵖ ⵉⵔⵎⴰⴷⵏ',
    'home.stats.candidates': 'ⵉⵎⵙⵙⴰⵔⴰⵏ ⵉⵜⵜⵓⵙⵏⵜⵍⵏ',
    'home.stats.parties': 'ⵉⴽⴰⴱⴰⵔⵏ ⵉⵙⵔⵜⴰⵏⵏ',
    'home.stats.satisfaction': 'ⴰⵔⵣⵓ ⵏ ⵉⵙⵙⵎⵔⵙⵏ',
    'home.features.title': 'ⵉⵎⴰⵙⵙⵏ ⵉⴷⵉⵎⵓⵇⵔⴰⵟⵉⵢⵏ ⵉⵎⵓⵔⵙⵏ',
    'home.features.subtitle': 'ⴽⵓⵍⵍⵓ ⵎⴰ ⵜⵃⵡⴰⵊⴷ ⴰⴷ ⵜⵙⴽⵔⴷ ⵜⵉⵔⵎⵉⵜⵉⵏ ⵜⵉⵙⵔⵜⴰⵏⵉⵏ ⵉⵜⵜⵓⵙⵙⴰⵏⵏ',
    'home.features.quiz.title': 'ⵜⴰⴱⵓⵚⵍⵜ ⵜⴰⵙⵔⵜⴰⵏⵜ',
    'home.features.quiz.description': 'ⴰⴼ ⵉⴽⴰⴱⴰⵔⵏ ⵉⵙⵔⵜⴰⵏⵏ ⵉⵎⵢⴰⵡⴰⵙⵏ ⴰⴽⴷ ⵜⵖⴰⵔⴰⵙⵉⵏ ⵏⵏⴽ ⵙ ⵓⵙⵙⴰⵖ ⵏⵏⵖ ⵉⵜⵜⵓⵙⴽⴰⵔⵏ ⵙ ⵜⵎⴰⵙⵙⴰⵏⵉⵏ.',
    'home.features.candidates.title': 'ⵉⴼⵔⵙⵏ ⵏ ⵉⵎⵙⵙⴰⵔⴰⵏ',
    'home.features.candidates.description': 'ⵙⵙⵉⵔⵉⵎ ⵉⵏⵖⵎⵉⵙⵏ ⵉⵎⵓⵔⵙⵏ ⵅⴼ ⵉⵎⵙⵙⴰⵔⴰⵏ ⴳ ⵜⵎⵏⴰⴹⵜ ⵏⵏⴽ ⴰⴽⴷ ⵉⵣⵔⴰⵏ ⴷ ⵉⴷⵖⴰⵔⵏ ⵉⵜⵜⵓⵙⵏⵜⵍⵏ.',
    'home.features.policies.title': 'ⴰⵎⴹⴼⴰⵕ ⵏ ⵉⵡⵓⵔⵉⵡⵏ',
    'home.features.policies.description': 'ⴹⴼⵕ ⵉⵡⵓⵔⵉⵡⵏ ⵉⵙⵔⵜⴰⵏⵏ ⴷ ⴰⴹⴼⵓⵔ ⵎⴰⵙ ⴰⴽⴽⵯ ⵉⴽⴰⴱⴰⵔⵏ ⴰⵔ ⵙⵙⴽⴰⵔⵏ ⵉⵡⵓⵔⵉⵡⵏ ⵏⵏⵙⵏ ⵉ ⵉⵎⵙⵙⴰⵖⵏ.',
    'home.features.events.title': 'ⵜⵉⵎⵙⴰⵔⵉⵏ ⵜⵉⵎⴷⴰⵏⵉⵏ',
    'home.features.events.description': 'ⵇⵇⵉⵎ ⵉⵜⵜⵓⵙⵙⴰⵏ ⵅⴼ ⵉⵎⵔⴰⵔⴰⵜⵏ, ⵜⵉⵎⵙⴰⵔⵉⵏ ⵏ ⵜⵎⴷⵉⵏⵜ, ⴷ ⵜⵉⵎⵙⴰⵔⵉⵏ ⵜⵉⵙⵔⵜⴰⵏⵉⵏ ⴳ ⵓⵎⵓⵏ ⵏⵏⴽ.',
    'home.cta.title': 'ⴷⴷⵓ ⵖⵔ ⵜⵏⵀⴹⴰ ⵜⴰⴷⵉⵎⵓⵇⵔⴰⵟⵉⵜ ⵜⴰⵎⵖⵔⵉⴱⵉⵜ',
    'home.cta.description': 'ⵉⵍⵉ ⴰⵙⴳⴰ ⵏ ⵓⵎⵓⵙⵙⵓ ⵉⵙⵙⵏⵖⵓⵔⵏ ⵜⴰⴷⵉⵎⵓⵇⵔⴰⵟⵉⵜ ⵙ ⵓⴷⵔⴰⵡ ⵉⵜⵜⵓⵙⵙⴰⵏⵏ ⴷ ⵓⴷⵔⴰⵡ ⴰⵎⴷⴰⵏ.',
    'home.cta.button': 'ⴱⴷⵓ ⴰⵏⵎⴰⵍⴰ ⵏⵏⴽ',
    
    // Quiz
    'quiz.title': 'ⴰⵙⵙⴰⵖ ⵏ ⵜⴱⵓⵚⵍⵜ ⵜⴰⵙⵔⵜⴰⵏⵜ',
    'quiz.subtitle': 'ⴰⴼ ⴰⵙⵙⴰⵔⵓ ⵏⵏⴽ ⴰⵙⵔⵜⴰⵏ',
    'quiz.description': 'ⵔⴰⵔ ⵅⴼ ⵉⵙⵇⵙⵉⵜⵏ ⵅⴼ ⵉⵎⵙⴰⵍⵏ ⵉⵙⵔⵜⴰⵏⵏ ⵉⵎⵖⵓⴷⴰⵏ ⴰⴷ ⵜⴰⴼⴷ ⵉⴽⴰⴱⴰⵔⵏ ⵉⵎⵖⵔⵉⴱⵉⵢⵏ ⵉⵙⵎⴰⵍⴰⵏ ⵜⵉⵔⵎⵉⵜⵉⵏ ⵏⵏⴽ.',
    'quiz.type.short': 'ⴰⵙⵙⴰⵖ ⴰⵣⵔⴱⴰⵏ',
    'quiz.type.full': 'ⴰⵙⵙⴰⵖ ⴰⵎⵓⵔⵙ',
    'quiz.type.short.description': '10 ⵉⵙⵇⵙⵉⵜⵏ ⵉⵎⵖⵓⴷⴰⵏ • 3 ⵜⵙⴷⴰⵜⵉⵏ',
    'quiz.type.full.description': '15 ⵉⵙⵇⵙⵉⵜⵏ ⵉⵎⵓⵔⵙⵏ • 5 ⵜⵙⴷⴰⵜⵉⵏ',
    'quiz.type.short.detail': 'ⵉⵖⵓⴷⴰ ⵉ ⵓⵙⵙⴰⵔⵓ ⴰⵣⵔⴱⴰⵏ ⵏ ⵓⵙⵙⴰⵔⵓ ⴰⵙⵔⵜⴰⵏ',
    'quiz.type.full.detail': 'ⴰⵙⵙⴼⵙⵉ ⴰⵎⵓⵔⵙ ⵏ ⵜⵉⵔⵎⵉⵜⵉⵏ ⵏⵏⴽ ⵜⵉⵙⵔⵜⴰⵏⵉⵏ',
    'quiz.question.counter': 'ⴰⵙⵇⵙⵉ {current} ⵙⴳ {total}',
    'quiz.progress': 'ⵉⵎⴷ {percent}%',
    'quiz.category.economic': 'ⵜⴰⵙⵔⵜⵉⵜ ⵏ ⵓⴷⵎⴰⵡⴰⵏ',
    'quiz.category.social': 'ⵉⵎⵙⴰⵍⵏ ⵏ ⵓⵎⵓⵏ',
    'quiz.category.foreign': 'ⵜⴰⵙⵔⵜⵉⵜ ⵏ ⴱⵕⵕⴰ',
    'quiz.category.environment': 'ⵜⴰⵡⵏⵏⴰⴹⵜ',
    'quiz.category.education': 'ⴰⵙⵙⵍⵎⴷ ⴷ ⵜⴷⵍⵙⴰ',
    'quiz.category.healthcare': 'ⵜⴰⴷⵓⵙⵉ',
    'quiz.category.technology': 'ⵜⵉⵜⵉⴽⵏⵓⵍⵓⵊⵉⵜ ⴷ ⵉⵣⵔⴼⴰⵏ',
    'quiz.answers.strongly_disagree': 'ⵓⵔ ⵎⵙⴰⵙⴰⵖ ⴱⴰⵀⵔⴰ',
    'quiz.answers.disagree': 'ⵓⵔ ⵎⵙⴰⵙⴰⵖ',
    'quiz.answers.neutral': 'ⴰⵏⴰⵎⵎⴰⵙ',
    'quiz.answers.agree': 'ⵎⵙⴰⵙⴰ',
    'quiz.answers.strongly_agree': 'ⵎⵙⴰⵙⴰ ⴱⴰⵀⵔⴰ',
    'quiz.results.title': 'ⴰⵙⵙⴰⵔⵓ ⵏⵏⴽ ⴰⵙⵔⵜⴰⵏ',
    'quiz.results.subtitle': 'ⵙ ⵓⵙⵉⵙ ⵏ ⵜⵔⴰⵔⵉⵏ ⵏⵏⴽ, ⵀⴰ ⵎⴰⵏⵎⴽ ⴰⵔ ⵜⵎⵢⴰⵡⴰⵙⴷ ⴰⴽⴷ ⵉⴽⴰⴱⴰⵔⵏ ⵉⵙⵔⵜⴰⵏⵏ ⵉⵎⵖⵔⵉⴱⵉⵢⵏ',
    'quiz.results.match': 'ⴰⵎⵢⴰⵡⴰⵙ {percent}%',
    'quiz.results.retake': 'ⴰⵍⵙ ⴰⵙⵙⴰⵖ',
    'quiz.results.share': 'ⴱⴹⵓ ⵉⵢⴰⴼⴰⴷⵏ',
    'quiz.results.download': 'ⴰⴳⵎ ⴰⵏⴰⵇⵇⵉⵙ',
    'quiz.results.disclaimer': 'ⵉⵢⴰⴼⴰⴷⵏ ⵙⵓⵍⵏ ⵅⴼ ⵉⵀⵔⵉⴽⵏ ⵏ ⵉⴽⴰⴱⴰⵔⵏ ⴷ ⵉⴷⵖⴰⵔⵏ ⵉⵖⵔⴼⴰⵏⵏ. ⵜⵉⵔⵎⵉⵜⵉⵏ ⵜⵉⵙⵔⵜⴰⵏⵉⵏ ⵔⵓⴽⴽⵙⵏⵜ ⴷ ⵓⵔ ⵉⵖⵢ ⴰⴷ ⵜⵜⵓⵙⵏⵜⵍⵏⵜ ⴰⴽⴽⵯ ⵙ ⵓⵙⵙⴰⵖ ⴰⴷ.',
    
    // Candidates
    'candidates.title': 'ⴰⵎⴰⴳⵔⴰⴷ ⵏ ⵉⵎⵙⵙⴰⵔⴰⵏ',
    'candidates.subtitle': 'ⵙⵙⵏ ⵉⵏⵎⴰⵍⴰⵏ ⵏⵏⴽ',
    'candidates.description': 'ⵙⵙⵉⵔⵉⵎ ⵉⴼⵔⵙⵏ ⵉⵎⵓⵔⵙⵏ ⵏ ⵉⵎⵙⵙⴰⵔⴰⵏ ⵉⵜⵜⵓⵙⵙⴰⵔⴰⵏ ⴳ ⵜⵎⵏⴰⴹⵜ ⵏⵏⴽ ⴰⴽⴷ ⵉⵏⵖⵎⵉⵙⵏ ⴷ ⵉⴷⵖⴰⵔⵏ ⵉⵙⵔⵜⴰⵏⵏ ⵉⵜⵜⵓⵙⵏⵜⵍⵏ.',
    'candidates.search.placeholder': 'ⵔⵣⵓ ⵉⵎⵙⵙⴰⵔⴰⵏ ⵙ ⵢⵉⵙⵎ...',
    'candidates.filter.region': 'ⵙⵜⵢ ⵜⴰⵎⵏⴰⴹⵜ',
    'candidates.filter.party': 'ⵙⵜⵢ ⴰⴽⴰⴱⴰⵔ',
    'candidates.filter.all_regions': 'ⴰⴽⴽⵯ ⵜⵎⵏⴰⴹⵉⵏ',
    'candidates.filter.all_parties': 'ⴰⴽⴽⵯ ⵉⴽⴰⴱⴰⵔⵏ',
    'candidates.location.detect': 'ⵙⵙⵎⵔⵙ ⴰⴷⵖⴰⵔ ⵉⵏⵓ',
    'candidates.location.detected': 'ⴰⵙⴽⵏ ⵏ ⵉⵎⵙⵙⴰⵔⴰⵏ ⵉ: {location}',
    'candidates.count': 'ⴰⵙⴽⵏ ⵏ {count} ⵉⵎⵙⵙⴰⵔⴰⵏ',
    'candidates.age': 'ⴰⵙⴳⴳⵯⴰⵙ {age}',
    'candidates.experience': 'ⵜⴰⵔⵎⵉⵜ',
    'candidates.view_profile': 'ⵥⵕ ⴰⴼⵔⵙ ⴰⵎⵓⵔⵙ',
    'candidates.no_results': 'ⵓⵔ ⵜⵜⵓⴰⴼⵏ ⵉⵎⵙⵙⴰⵔⴰⵏ',
    'candidates.no_results.description': 'ⴰⵔⵎ ⴰⴷ ⵜⵙⵏⴼⵍⴷ ⵉⵙⴱⴷⴰⴷⵏ ⵏ ⵓⵔⵣⵣⵓ ⵏⵏⴽ ⵏⵖ ⵓⵖⵓⵍ ⴷⴰⵜ',
    
    // Policies
    'policies.title': 'ⴰⵎⴹⴼⴰⵕ ⵏ ⵉⵡⵓⵔⵉⵡⵏ ⵉⵙⵔⵜⴰⵏⵏ',
    'policies.subtitle': 'ⴰⵙⵙⴰⵖⵏ ⵙ ⵜⴼⵔⵔⴰ',
    'policies.description': 'ⴹⴼⵕ ⵉⵡⵓⵔⵉⵡⵏ ⵉⵙⵔⵜⴰⵏⵏ ⴷ ⵥⵕ ⵎⴰⵏⵎⴽ ⴰⵔ ⵙⵙⴽⴰⵔⵏ ⵉⴽⴰⴱⴰⵔⵏ ⵉⵡⵓⵔⵉⵡⵏ ⵏⵏⵙⵏ ⵉ ⵉⵎⵣⴷⴰⵖ ⵉⵎⵖⵔⵉⴱⵉⵢⵏ.',
    'policies.search.placeholder': 'ⵔⵣⵓ ⴳ ⵉⵡⵓⵔⵉⵡⵏ ⵉⵙⵔⵜⴰⵏⵏ...',
    'policies.filter.status': 'ⵙⴼⵍ ⵙ ⵓⴷⴷⴰⴷ',
    'policies.filter.category': 'ⵙⴼⵍ ⵙ ⵜⴰⴳⴳⴰⵢⵜ',
    'policies.filter.party': 'ⵙⴼⵍ ⵙ ⵓⴽⴰⴱⴰⵔ',
    'policies.status.completed': 'ⵉⵎⴷ',
    'policies.status.in_progress': 'ⴰⵔ ⵉⵜⵜⵓⵙⴽⴰⵔ',
    'policies.status.not_started': 'ⵓⵔ ⵉⴱⴷⵓ',
    'policies.status.broken': 'ⴰⵡⵓⵔⵉ ⵉⵜⵜⵓⵔⵣⵏ',
    'policies.count': 'ⴰⵙⴽⵏ ⵏ {count} ⵉⵡⵓⵔⵉⵡⵏ ⵉⵙⵔⵜⴰⵏⵏ',
    'policies.promised_date': 'ⵉⵜⵜⵓⵡⵓⵔⵉ ⴳ: {date}',
    'policies.progress': 'ⴰⵙⴱⵓⵖⵍⵓ: {percent}%',
    'policies.sources': 'ⵉⵙⵓⴳⴰⵎ:',
    'policies.no_results': 'ⵓⵔ ⵜⵜⵓⴰⴼⵏ ⵜⵙⵔⵜⵉⵏ',
    'policies.no_results.description': 'ⴰⵔⵎ ⴰⴷ ⵜⵙⵏⴼⵍⴷ ⵉⵙⴱⴷⴰⴷⵏ ⵏ ⵓⵔⵣⵣⵓ ⵏⵏⴽ',
    
    // Events
    'events.title': 'ⴰⵙⵏⵙⵉ ⵏ ⵜⵉⵎⵙⴰⵔⵉⵏ ⵜⵉⵙⵔⵜⴰⵏⵉⵏ',
    'events.subtitle': 'ⵇⵇⵉⵎ ⵉⵜⵜⵓⴷⵔⴰⵡⵏ',
    'events.description': 'ⴰⴼ ⵜⵉⵎⵙⴰⵔⵉⵏ ⵜⵉⵙⵔⵜⴰⵏⵉⵏ ⵉⴷ ⵉⵜⵜⵓⵙⵏ, ⵉⵎⵔⴰⵔⴰⵜⵏ, ⴷ ⵜⵉⵔⵓⴱⴱⴰ ⵏ ⵓⴷⵔⴰⵡ ⴰⵎⴷⴰⵏ ⴳ ⵜⵎⵏⴰⴹⵜ ⵏⵏⴽ.',
    'events.filter.type': 'ⴰⵏⴰⵡ ⵏ ⵜⵎⵙⴰⵔⵜ',
    'events.filter.region': 'ⵜⴰⵎⵏⴰⴹⵜ',
    'events.filter.date': 'ⵙⴳ ⵓⵙⴰⴽⵓⴷ',
    'events.type.debate': 'ⴰⵎⵔⴰⵔⴰ',
    'events.type.town_hall': 'ⴰⵙⴰⵔⴰⴳ ⵏ ⵜⵎⴷⵉⵏⵜ',
    'events.type.rally': 'ⴰⵙⵎⵓⵏ',
    'events.type.info_session': 'ⵜⵉⵎⵙⴰⵔⵜ ⵏ ⵉⵏⵖⵎⵉⵙⵏ',
    'events.count': 'ⴰⵙⴽⵏ ⵏ {count} ⵜⵉⵎⵙⴰⵔⵉⵏ',
    'events.attendees': '{count} ⵉⵎⴷⵔⴰⵡⵏ',
    'events.max_attendees': ' / {max} ⴷ ⵓⴳⴳⴰⵔ',
    'events.organized_by': 'ⵉⵜⵜⵓⵙⴷⴱⴰⵔ ⵙⴳ: {organizer}',
    'events.add_calendar': 'ⵔⵏⵓ ⵖⵔ ⵓⵙⵏⵙⵉ',
    'events.register': 'ⴰⵔⴰ',
    'events.view_details': 'ⵥⵕ ⵉⴼⵔⴷⵉⵙⵏ',
    'events.online': 'ⵅⴼ ⵉⵏⵜⵉⵔⵏⵉⵜ',
    'events.past_event': 'ⵜⴰⵎⵙⴰⵔⵜ ⵉⵣⵔⵉⵏ',
    'events.no_results': 'ⵓⵔ ⵜⵜⵓⴰⴼⵏ ⵜⵉⵎⵙⴰⵔⵉⵏ',
    'events.no_results.description': 'ⴰⵔⵎ ⴰⴷ ⵜⵙⵏⴼⵍⴷ ⵉⵙⴱⴷⴰⴷⵏ ⵏ ⵓⵔⵣⵣⵓ ⵏⵏⴽ ⵏⵖ ⵓⵖⵓⵍ ⴷⴰⵜ ⵉ ⵜⵉⵎⵙⴰⵔⵉⵏ ⵜⵉⵎⴰⵢⵏⵓⵜⵉⵏ',
    
    // Footer
    'footer.description': 'ⴰⵙⵙⵏⵖⵓⵔ ⵏ ⵉⵎⵣⴷⴰⵖ ⵉⵎⵖⵔⵉⴱⵉⵢⵏ ⴰⴷ ⵙⴽⵔⵏ ⵜⵉⵔⵎⵉⵜⵉⵏ ⵏ ⵓⵙⵙⴰⵖ ⵉⵜⵜⵓⵙⵙⴰⵏⵏ ⵙ ⵜⵜⵉⴽⵏⵓⵍⵓⵊⵉⵜ, ⵜⴼⵔⵔⴰ, ⴷ ⵓⴷⵔⴰⵡ ⴰⵎⴷⴰⵏ.',
    'footer.links.about': 'ⵅⴼⵏⵏⵖ',
    'footer.links.how_it_works': 'ⵎⴰⵏⵎⴽ ⴰⵔ ⵉⵜⵜⵓⵙⴽⴰⵔ',
    'footer.links.privacy': 'ⵜⴰⵙⵔⵜⵉⵜ ⵏ ⵜⵓⴷⵔⵜ',
    'footer.links.terms': 'ⵜⵉⴼⴰⴷⵉⵏ ⵏ ⵓⵙⵙⵎⵔⵙ',
    'footer.support.help': 'ⴰⵎⵎⴰⵙ ⵏ ⵓⵡⵙ',
    'footer.support.contact': 'ⵎⵢⴰⵡⴰⴹ ⴰⴽⵯⴷⵏⵏⵖ',
    'footer.support.report': 'ⵎⵍ ⵅⴼ ⵓⴳⴷⵉⵍ',
    'footer.support.feedback': 'ⵜⵉⵔⵎⵉⵜⵉⵏ',
    'footer.copyright': '© 2025 ⵜⴰⵏⴰⴱⴰⴹⵜ ⴰⵙⵙⴰⵖ ⵏⵏⴽ ⵉⵙⵙⴰⵡⴰⵍ. ⵉⵜⵜⵓⵙⴽⴰⵔ ⵙ ⵓⵢⵓⵍ ⵉ ⵍⵎⵖⵔⵉⴱ.',
    'footer.tagline': 'ⴰⵙⵙⵏⵖⵓⵔ ⵏ ⵜⴼⵔⵔⴰ ⴷ ⵓⴷⵔⴰⵡ ⴰⴷⵉⵎⵓⵇⵔⴰⵟⵉⵢ',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || translations.en[key] || key;
    
    // Replace parameters in translation
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, value);
      });
    }
    
    return translation;
  };

  const isRTL = language === 'ar';
  const direction = isRTL ? 'rtl' : 'ltr';
  
  const getFontClass = () => {
    switch (language) {
      case 'ar': return 'font-arabic';
      case 'ber': return 'font-tifinagh';
      case 'fr': return 'font-french';
      default: return 'font-english';
    }
  };

  const fontClass = getFontClass();

  // Apply direction and font to document
  useEffect(() => {
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
    document.body.className = fontClass;
  }, [direction, language, fontClass]);

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      isRTL, 
      direction, 
      fontClass 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};